# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  getting-started-smoke-test:
    orbs:
      android: circleci/android@2.0.0
      aws-cli: circleci/aws-cli@3.1.1

    jobs:
      android:
        working_directory: ~/android-canaries/canaries/example
        executor:
          name: android/android-machine
          resource-class: xlarge
          tag: 2022.03.1
        steps:
          - checkout
          - aws-cli/setup:
              role-arn: ${AWS_ROLE_ARN}
          - run: lslrasdt
          - run:
              name: Invoking lambda
              command: |
                payload="{\"jobName\": \"${CIRCLE_JOB}\", \"projectRepoName\": \"${CIRCLE_PROJECT_REPONAME}\"}"
                echo $payload
                aws lambda invoke --function-name CircleCIWorkflowFailureHandler --payload "$payload" --cli-binary-format raw-in-base64-out response.json
              when: on_fail



workflows:
  canaries:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "Canaries", << pipeline.schedule.name >> ]
    jobs:
      - getting-started-smoke-test/android